services:
 postgres-db:
    image: postgres
    environment:
      - POSTGRES_MULTIPLE_DATABASES=nuber_eats,nuber_eats_test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"
      

  